const OpenAI = require("openai");
const puppeteer = require("puppeteer")


const openrouter = new OpenAI({
    baseURL: "https://openrouter.ai/api/v1",
    apiKey: process.env.OPENROUTER_API_KEY,
});


async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const prompt = `Generate an interview report for a candidate with the following details:
Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}

Respond with ONLY a valid JSON object with exactly these keys:
- "matchScore": number (0-100) indicating how well the candidate matches the job
- "title": string - the job title
- "technicalQuestions": array of objects with "question", "intention", "answer"
- "behavioralQuestions": array of objects with "question", "intention", "answer"
- "skillGaps": array of objects with "skill", "severity" (one of "low", "medium", "high")
- "preparationPlan": array of objects with "day" (number), "focus" (string), "tasks" (array of strings)`

    const response = await openrouter.chat.completions.create({
        model: "google/gemini-2.0-flash-001",
        messages: [
            { role: "system", content: "You are an expert interview coach and career advisor. Respond ONLY with valid JSON. No markdown, no code fences, no extra text." },
            { role: "user", content: prompt }
        ],
        response_format: { type: "json_object" },
    })

    return JSON.parse(response.choices[0].message.content)
}



async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4",
        margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const prompt = `Generate resume for a candidate with the following details:
Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}

The response should be a JSON object with a single field "html" which contains the HTML content of the resume.
The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience.
The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
The content of resume should not sound like it's generated by AI and should be as close as possible to a real human-written resume.
You can highlight the content using some colors or different font styles but the overall design should be simple and professional.
The content should be ATS friendly. The resume should ideally be 1-2 pages long when converted to PDF.`

    const response = await openrouter.chat.completions.create({
        model: "google/gemini-2.0-flash-001",
        messages: [
            { role: "system", content: "You are an expert resume writer. Respond ONLY with valid JSON containing a single key 'html'. No markdown, no code fences, no extra text." },
            { role: "user", content: prompt }
        ],
        response_format: { type: "json_object" },
    })

    const jsonContent = JSON.parse(response.choices[0].message.content)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
}

module.exports = { generateInterviewReport, generateResumePdf }